package ucbp.tfs.reports.fxform1

import java.util.List;
import java.util.Map;

import org.apache.commons.lang.StringUtils

class FxForm1Schedule7Service {
	
	def fxForm1DataQueryService
	
	public List<Map<String, Object>> getFxForm1Schedule7DataList(String onlineReportDate) {
				
		String getSchedule7Query =
		"""
			SELECT
			'000470' AS BANKCDE,
			REPLACE(DATE(TS.PROCESSDATE), '-', '') AS REFDATE,
			'TRD07' AS FORMNO,
			'200' AS TRANCDE,
			RPAD(
				('FXLC ' || 
					CASE WHEN TS.DOCUMENTSUBTYPE1='CASH' THEN 'CASH '
						ELSE 'REGULAR TO CASH '
					END 
				|| TS.SERVICETYPE), 40, ' '
			) AS DESC40,
			TS.CURRENCY AS CURRCDE,
			LPAD(REPLACE(RIGHT(LC.BSPCOUNTRYCODE, 3), ' ', ''), 3, '0') AS CTRYCDE,
			'1' AS BOOKCDE,
			CASE	
				WHEN TS.CURRENCY='USD' THEN TS.AMOUNT
				WHEN TS.CURRENCY='PHP' THEN TS.AMOUNT / TS.SPECIALRATEURR
			ELSE TS.AMOUNT * TS.SPECIALRATETHIRDTOUSDSERVICECHARGE
			END AS AMTDOLR,
		
			-- for report fields
			REPLACE(LC.DOCUMENTNUMBER, '-', '') AS DOCUMENTNUMBER,
			UPPER(LC.IMPORTERNAME) AS IMPORTERNAME,
			LC.IMPORTERCIFNUMBER,
			TS.SERVICEINSTRUCTIONID AS ETSNUMBER,
			TS.STATUS
			
		FROM LETTEROFCREDIT LC
		LEFT JOIN TRADEPRODUCT TP ON LC.DOCUMENTNUMBER=TP.DOCUMENTNUMBER
		LEFT JOIN TRADESERVICE TS ON LC.DOCUMENTNUMBER=TS.TRADEPRODUCTNUMBER
		WHERE
			TS.DOCUMENTTYPE='FOREIGN' AND TS.DOCUMENTCLASS='LC' AND TS.PAYMENTSTATUS='PAID' AND
			(
				(TS.DOCUMENTSUBTYPE1='CASH' AND TS.SERVICETYPE IN ('OPENING', 'AMENDMENT', 'CANCELLATION')) 
				OR (TS.DOCUMENTSUBTYPE1='REGULAR' AND TS.SERVICETYPE='ADJUSTMENT')
			)
			AND TS.STATUS IN ('APPROVED', 'POST_APPROVED', 'POSTED')
			AND DATE(TS.PROCESSDATE)='$onlineReportDate'
		"""

		def schedule7ResultQuery = fxForm1DataQueryService.getTfsResultFromQuery(getSchedule7Query, "")
		
		return schedule7ResultQuery
	}

}
